# From github.com/weaveworks/flagger artifacts/flagger/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
  namespace: istio-system
  labels:
    app: flagger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flagger
  template:
    metadata:
      labels:
        app: flagger
      annotations:
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: flagger
      containers:
      - name: flagger
        # image: weaveworks/flagger:0.18.2
        image: andrewjjenkins/flagger:mirror
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        command:
        - ./flagger
        - -log-level=info
        - -control-loop-interval=10s
        - -mesh-provider=istio
        - -metrics-server=http://prometheus.istio-system.svc.cluster.local:9090
        livenessProbe:
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=2
            - --spider
            - http://localhost:8080/healthz
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=2
            - --spider
            - http://localhost:8080/healthz
          timeoutSeconds: 5
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "32Mi"
            cpu: "10m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
